class houseinfo:
    releasetime = ''
    housecode = ''
    houseaddress = ''
    community = ''
    area = ''
    total = ''
    unitprice = ''
    storey = ''
    detailurl = ''
    downpayment = ''
    createdate = ''
    housetype = ''
    latitude = ''
    longitude = ''
